### PR TITLE
Added cryptocurrency conversion view and its activity test [US #130, Task#132]

### PR DESCRIPTION
**Pull request by miisaka**
User Story #108
Task #130 #132 

### WHAT kind of change does this PR introduce?
* Added a new activity to be able to perform cryptocurrency conversions between the major coins BTC, ETH, XRP and USD fiat.
* Added tests for this activity

ezgif-1-3fdd1620cd

...

### HOW is this accomplished?
By adding a new button on the main activity screen menu that will launch the new cryptocurrency conversion view.
...

### Checklist
- [x] Docs have been added / updated to reflect the changes
- [x] I have reviewed and tested the changes :white_check_mark:
- [x] I have squashed my commits to have a reasonable amount of commits
- [x] All of the code I have written adhere to the coding conventions outlined in the coding conventions section of the wiki

### CODE REVIEW

**Comment by 0matleb2** [comment]
This is not an extensible design, as the number of buttons required for each conversion pair scales with the factorial of the number of currencies.

This would be more appropriately integrated into the currency conversion view in the money activity. For example, a ‘toggle crypto button’ could be added to beside each spinner to individually swap the fiat selection spinner with a crypto selection spinner, and the conversion fetch task could be altered to also grab crypto rates. This will allow for conversion between any crypto/crypto, crypto/fiat, fiat/fiat pair, while maintaining the ability to perform other money calculator operations (basic arithmetic, tip, tax) on the result.

**Comment by izconcept** [comment]
Can this feature be implemented in the money view instead. It seems like it would fit better as an extension to that view since we already have the same feature in that view for regular currencies.

**Comment by 0matleb2** [comment]
It was discussed that switching this feature to use spinners instead of buttons would cause excess difficulty in testing the feature. This is due to a known issue with Travis CI running espresso tests on Spinners.

**Comment by jusleg** [comment]
Small comment, instead of using `->` why not use `→`

**Comment by miisaka** [comment]
This PR will be closed and a new PR with the whole new feature will be opened upon its completion.

**Pull request closed without merging**
